# Import the relevant libraries

In [1]:
import numpy as np

# Declaring scalars, vectors, and matrices

In [2]:
s = 5

In [4]:
s

5

## Vectors

In [5]:
v = np.array([5,-2,4])

In [6]:
v

array([ 5, -2,  4])

## Matrix

In [7]:
m = np.array([[5,12,6],[-3,0,14]])

In [9]:
m

array([[ 5, 12,  6],
       [-3,  0, 14]])

## Tensor

In [33]:
m1 = np.array([[5,12,6],[-3,0,14]])
m1

array([[ 5, 12,  6],
       [-3,  0, 14]])

In [32]:
m2 = np.array([[9,8,7],[1,3,-5]])
m2

array([[ 9,  8,  7],
       [ 1,  3, -5]])

In [34]:
t = np.array([m1,m2])
t

array([[[ 5, 12,  6],
        [-3,  0, 14]],

       [[ 9,  8,  7],
        [ 1,  3, -5]]])

## Manually creating a Tensor

In [39]:
t_manual = np.array([[[ 5, 12,  6], [-3,  0, 14]], [[ 9,  8,  7], [ 1,  3, -5]]])
t_manual

array([[[ 5, 12,  6],
        [-3,  0, 14]],

       [[ 9,  8,  7],
        [ 1,  3, -5]]])

## Data types

In [10]:
type(s)

int

In [11]:
type(v)

numpy.ndarray

In [13]:
type(m)

numpy.ndarray

In [14]:
s_array = np.array(5)

In [15]:
s_array

array(5)

In [35]:
type(s_array)

numpy.ndarray

In [36]:
type(t)

numpy.ndarray

## Data shapes

In [18]:
m.shape

(2, 3)

In [19]:
v.shape

(3,)

In [22]:
v.reshape(1,3)

array([[ 5, -2,  4]])

In [37]:
v.reshape(3,1)

array([[ 5],
       [-2],
       [ 4]])

In [38]:
t.shape

(2, 2, 3)

In [24]:
s_array.shape

()

In [28]:
s.shape # This is a zero dimentional object

AttributeError: 'int' object has no attribute 'shape'

**Scalar**
- A vector of length 1
- a 1x1 matrix
***
**Vector**
- Each element is a scalar
- 1xm or mx1 matrix
***
**Matrix**
- A collection of vectors/scalars
- Dimensions: mxn
***
**Tensors**
- A generalization of all the concepts above
- Scalar - Tensor of rank 0
- Vector - Tensor of rank 1
- Matrix - Tensor of rank 2

## Addition of Matrices

In [40]:
m1

array([[ 5, 12,  6],
       [-3,  0, 14]])

In [41]:
m2

array([[ 9,  8,  7],
       [ 1,  3, -5]])

In [42]:
m1+m2

array([[14, 20, 13],
       [-2,  3,  9]])

## Subtraction

In [43]:
m1-m2

array([[-4,  4, -1],
       [-4, -3, 19]])